name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.4
  redux_logging: ^0.3.0
  redux_navigator:
    path: ../../redux_navigator

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
