name: redux_navigator
description: A Redux middleware for Navigator of Flutter. You can use default Navigator related Action, and also add custom behaviors.
version: 0.2.1
author: Ryunosuke Watanabe <heavenosk@gmail.com>
homepage: https://github.com/HeavenOSK/redux_navigator
environment:
  sdk: ">=2.2.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  redux: ^4.0.0
  redux_heaven: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.4.0
flutter:
